version: '3.8'

services:
  telegram-docker-bot:
    build: .
    container_name: telegram-docker-bot
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - SERVER_HOST=${SERVER_HOST}
      - SERVER_USER=${SERVER_USER}
      - SERVER_PASSWORD=${SERVER_PASSWORD}
    volumes:
      - ./logs:/app/logs
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge
